### ISSUE TITLE
Question regarding Ticker + Data Race issue

### ISSUE THREAD

**Issue by mjeshtri** [gemnasium/logrus-postgresql-hook#9]
Hello, 

I have 2 questions/concerns, which seem to be related: 

1. I would like to ask about the rationale behind setting the  `*time.Ticker` to 1 second when the new async hook is created 
https://github.com/gemnasium/logrus-postgresql-hook/blob/102da181ba3a5ba51f595f614f6c873e096d4e9f/postgresql_hook.go#L77

and then overwriting this time ticker with a 'quicker' one in the `Flush()` method 
https://github.com/gemnasium/logrus-postgresql-hook/blob/102da181ba3a5ba51f595f614f6c873e096d4e9f/postgresql_hook.go#L172

2.  When running the test with race condition on _i.e._ with `-race` flag, there is data racing problem.  While one goroutine tries to write to `hook.Ticker` in `Flush()` method, another one want to read in `fire()` method, line 202.

Here is the output that I get when running test with race condition:
![screenshot from 2019-03-05 15-55-02](https://user-images.githubusercontent.com/27018375/53814753-88709280-3f60-11e9-94ab-09950bc50966.png)

Thank you!

**Comment by gravis** [comment]
Thanks for reporting it. I'm not sure I understand your first point. Is there a question there?

**Comment by mjeshtri** [comment]
Hi,
Yes, in the first point what I am asking is: Why are you overwriting the ticker channel (which is created at async hook) in `Flush()` method?

**Comment by gravis** [comment]
I don't see a quick solution for this problem, I will try to figure out something in the next days. Please feel free to suggest something if you have that in mind already :)

**Comment by gravis** [comment]
Good question! It's just to exit quicker. With a ticker at 1 second, it can take up to 1s to exit the program.

**Comment by mjeshtri** [comment]
What do you think if the default ticker in `NewAsyncHook`  is set as `hook.Ticker = time.NewTicker(300 * time.Millisecond)` and  setting the ticker in  `Flush()` is completely removed?  This solves the concurrency problem.

I can create a PR if you are OK with that.
